### ISSUE TITLE
Links broken on wiki

### ISSUE THREAD

**Issue by Spone** [wildbit/mailmason#33]
Hello,

all the links to the examples on [this page](https://github.com/wildbit/mailmason/wiki/About#what-templates-are-included) are broken, I get an S3 error:

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>A116E771F9CE9625</RequestId>
  <HostId>TXWC1WrmFqhcwBAM87qR4zm50lQj1tJsoPMtK4Asg2Rt4+yITaBMhQgzbHUwcOKfXAVV4+YwAr0=</HostId>
</Error>
```

**Comment by matt-west** [comment]
Thanks for letting us know @Spone. Those links should be working again now.
