### ISSUE TITLE
Outlook dark mode buttons weird background

### ISSUE THREAD

**Issue by beardo01** [wildbit/mailmason#48]
Hey,

The dark mode templates in Outlook render with a strange background:

![image](https://user-images.githubusercontent.com/11054688/81174640-8b906400-8fe5-11ea-8bf8-d5c154654a1d.png)

Thanks!

**Comment by derekrushforth** [comment]
Hey @beardo01, sorry for the late response here. I'm getting around to fixing these issues. I couldn't reproduce this in Litmus. 

Are you seeing this in outlook.com or in the desktop client? What OS are you using? And does the link contain a valid URL? Outlook sometimes botches the link styling if it contains an invalid URL.

Thanks!

**Comment by beardo01** [comment]
Hey @derekrushforth, no problems at all. I appreciate it!

I am experiencing this on Outlook for Mac (specifically Version 16.37) as well on iOS. The link does contain a valid URL. If it'd be useful I can share the template and a compiled example for you.

Cheers!

**Comment by derekrushforth** [comment]
@beardo01 That'd be great if you can send the template HTML. You can send it to [derek@wildbit.com](mailto:derek@wildbit.com).

**Comment by beardo01** [comment]
@derekrushforth, I've forwarded you a copy of one of the emails and also set up a repo with the project files [here](https://github.com/beardo01/mailmason). Let me know if you need anything else!

**Comment by shemming** [comment]
Has there been any progress on this? I also see this coloring on Outlook for Mac.

**Comment by derekrushforth** [comment]
@shemming, are you seeing this with the default MailMason button colors? Or are you using different button colors? 

It looks like Outlook on MacOS automatically changes the button's background color if there isn't enough contrast between that and the text. The default colors on MailMason's buttons shouldn't have an issue, but if you're using something lighter adding a linear-gradient to the button background should do the trick.

See https://github.com/beardo01/mailmason/pull/3 for more details.

**Comment by shemming** [comment]
Thanks for the quick response, it looks like it was just an issue with custom colors!
